### ISSUE TITLE
LibWeb: Get Pixedit fully functional

### ISSUE THREAD

**Issue by circl-lastname** [LadybirdWebBrowser/ladybird#102]
[Pixedit](https://circl-lastname.github.io/Pixedit/) is an online pixel editor that I created and wish to have fully compatible with Ladybird. There are a couple issues that I wish to fix.

Visual issues:
- [X] Resizing has weird behavior (#20870)
  - [ ] Sideyak: Add more presentational hints
- [x] measureText off for both vector and bitmap fonts (#21340)
- [ ] Text is not rendered from the baseline, add actual implementation of baseline

Functionality issues:
- [X] Moving around the drawing area doesn't work (#20749)
- [X] Open doesn't work. File dialogs not implemented (#23346)
- [x] Open doesn't work. createImageBitmap not implemented (#23850)
- [ ] Save doesn't work. `download` attribute for `<a>` not implemented
- [x] Add color doesn't work. Color dialogs not implemented (#20951,  #21244)
  - [x] Sideyak: Improve look of `<input type="color">` elements (#21438)
- [ ] Keyboard shortcuts not working in Ladybird Qt. e.key = "Unidentified"
